sudo: required

language: python

env:
  - VER=1.0.0

services:
  - docker

before_install:
  - eval $(./set-travis-env.sh)
  - docker pull emccode/mesos-libstorage-build:${VER}

install:
  - docker run -ti -v $TRAVIS_BUILD_DIR/isolator/:/isolator emccode/mesos-libstorage-build:${VER} /bin/bash -c  '/usr/bin/make all && cp -p -v /isolator/build/.libs/libmesos_libstorage_isolator-${ISOLATOR_VERSION}.so /isolator/'
  - docker logs $(docker ps -l -q)
  - mv $TRAVIS_BUILD_DIR/isolator/libmesos_libstorage_isolator-${VER}.so $TRAVIS_BUILD_DIR/isolator/${SO_FILENAME}

script:
  - shasum $TRAVIS_BUILD_DIR/isolator/${SO_FILENAME}

before_deploy:
  - ls -la $TRAVIS_BUILD_DIR/isolator/
  - cat bintray-unstable-filtered.json

deploy:
  - provider: bintray
    file: bintray-unstable-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true